# Generated by Django 5.2 on 2025-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Annual', 'Annual'), ('Maternity', 'Maternity')], max_length=20),
        ),
    ]
