# Generated by Django 5.2 on 2025-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_leave_applied_on_remove_leave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
