# Generated by Django 5.2 on 2025-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/images_img.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
