# Generated by Django 5.2 on 2025-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
