# Generated by Django 5.2 on 2025-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
            preserve_default=False,
        ),
    ]
