# Generated by Django 5.2 on 2025-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
