# Generated by Django 5.2 on 2025-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/files/'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Untitled Report', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default='Test'),
            preserve_default=False,
        ),
    ]
